# Generated by Django 4.2 on 2025-09-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'GOVERNMENT'), ('ECONONMY', 'ECONOMY'), ('TECHNOLOGY', 'TECHNOLOGY'), ('EDUCATION', 'EDUCATION'), ('FARMING', 'FARMING')], max_length=100, null=True),
        ),
    ]
