# Generated by Django 4.2 on 2025-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_profile_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
